# Generated by Django 2.1.8 on 2019-09-29 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_text', models.TextField(null=True)),
                ('article_url', models.TextField(null=True)),
                ('html_template', models.TextField(blank=True, null=True)),
                ('plain_text', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(default=datetime.datetime(2019, 9, 29, 9, 1, 0, 972500))),
                ('template_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
